### ISSUE TITLE
ExceptionInInitializerError on command execution

### ISSUE THREAD

**Issue by SlimeDog** [InstantlyMoist/xRay#6]
Spigot 1.16.3
xRay 3.121

/xray
produces error in-game and
```
[13:37:41] [Server thread/INFO]: rambeau issued server command: /xray
[13:37:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'xray' in plugin xRay v3.121
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at me.kyllian.xRay.threads.ChunkThread.startTask(ChunkThread.java:46) ~[?:?]
        at me.kyllian.xRay.tasks.ChunkTask.lambda$send$0(ChunkTask.java:30) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at me.kyllian.xRay.tasks.ChunkTask.send(ChunkTask.java:30) ~[?:?]
        at me.kyllian.xRay.handlers.XRayHandler.send(XRayHandler.java:21) ~[?:?]
        at me.kyllian.xRay.commands.CMD_xRay.onCommand(CMD_xRay.java:37) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        ... 18 more
Caused by: java.lang.RuntimeException: Unable to find MultiBlockChangeInfo (PacketPlayOutMultiBlockChange$MultiBlockChangeInfo)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2101) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getMultiBlockChangeInfoClass(MinecraftReflection.java:1848) ~[?:?]
        at com.comphenix.protocol.wrappers.MultiBlockChangeInfo.<clinit>(MultiBlockChangeInfo.java:38) ~[?:?]
        at me.kyllian.xRay.threads.ChunkThread.startTask(ChunkThread.java:46) ~[?:?]
        at me.kyllian.xRay.tasks.ChunkTask.lambda$send$0(ChunkTask.java:30) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at me.kyllian.xRay.tasks.ChunkTask.send(ChunkTask.java:30) ~[?:?]
        at me.kyllian.xRay.handlers.XRayHandler.send(XRayHandler.java:21) ~[?:?]
        at me.kyllian.xRay.commands.CMD_xRay.onCommand(CMD_xRay.java:37) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar-2020-10-17-1639:git-Spigot-57bbdd8-b8dd5ec]
        ... 18 more
```

**Comment by SlimeDog** [comment]
Error still occurs with the second version 3.121.

**Comment by InstantlyMoist** [comment]
See where this is coming from... 

https://github.com/dmulloy2/ProtocolLib/issues/956 
Issue due to ProtocolLib changing in 1.16.2... Will be looking into this.

**Comment by SlimeDog** [comment]
We all adjust our plugins to changes in dependencies. Overview says:
> Dependencies:............................ProtocolLib Make sure to use the latest build!

but that fails.

**Comment by InstantlyMoist** [comment]
> We all adjust our plugins to changes in dependencies. Overview says:
> 
> > Dependencies:............................ProtocolLib Make sure to use the latest build!
> 
> but that fails.

Understood, problem is that Protocollib changed their packets under the hood. Currently working towards a fix.

**Comment by InstantlyMoist** [comment]
Managed to rewrite base for 1.16.3 support. Only issue now is there is no (proper) way of reverting chunks in this case. Will be looking into it more. Releasing update now, just keep in mind reverting does not work.

**Comment by SlimeDog** [comment]
Please clarify what "reverting" means.
